apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}
  labels:
{{ include "prometheus-exporter.labels" . | indent 4 }}
  annotations:
    prometheus.path: "/"
    prometheus.scrape: "true"
    prometheus.port: "5000"
    prometheus.scheme: "http"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: container-port 
      protocol: TCP
      name: exposed-service
  selector:
    app.kubernetes.io/name: {{ include "prometheus-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
