apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}
  labels:
{{ include "prometheus-exporter.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: fpl-exporter
      release: metrics
  namespaceSelector:
    matchNames:
      - exporter
  endpoints:
  - port: container-port
    path: /
